### ISSUE TITLE
trailing function call parenthesis regression in 0.40

### ISSUE THREAD

**Issue by ZacSweers** [facebookincubator/ktfmt#348] opened 2022-09-04 16:10 UTC
Noticed this while upgrading today - trailing function calls are getting (in some cases) their closing paren moved to the next line despite no parameters being present.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/1361086/188322908-b7950f1c-aa54-49f0-92bd-105e23e5db06.png">

This is our repro file for this (`illegal_tasks.gradle.kts`)

```kotlin
fun configureIllegalTaskChecks() {
  // Map of illegal task name -> preferred alternative
  val illegalTaskNames =
    mapOf(
      ":build" to ":app:assembleInternalDebug",
      ":assemble" to ":app:assembleInternalDebug",
      ":assembleDebug" to ":app:assembleInternalDebug",
      ":assembleRelease" to ":app:assembleExternalRelease",
      ":lint" to ":app:lintDebug",
      ":lintDebug" to ":app:lintDebug"
    )

  // Some of these tasks don't actually exist at the top level, so we need to create them
  tasks.maybeCreate("assemble")
  tasks.maybeCreate("assembleDebug")
  tasks.maybeCreate("lint")
  tasks.maybeCreate("lintDebug")

  gradle.taskGraph.whenReady {
    val graph = this
    illegalTaskNames.forEach { (key, value) ->
      if (graph.hasTask(key)) {
        throw StopExecutionException(
          """
          Please use "./gradlew $value" (or whatever the right specific task is) instead of "./gradlew $key"

          `./gradlew $key` is an umbrella task that runs a number of other tasks that are not required for local development. Running the recommended task will give you much faster build speeds and avoid unexpected errors.
          This can often happen if you click the "hammer" build icon in the IDE without selecting the appropriate project first.
          """.trimIndent()
        )
      }
    }
  }
}

if (!hasProperty("skipIllegalTaskChecks")) {
  configureIllegalTaskChecks()
}
```

**Comment by davidtorosyan** [comment] 2022-09-06 23:26
Thanks for reporting this! It's an interesting edge case.

Specifically, it looks like this issue happens when:
1. You're using --google-style
2. There's a multiline string whose contents are longer than the maximum line length
3. The function has zero arguments

It's indeed a regression, and a fix is in progress.

**Closed** 2022-09-07 17:09 UTC

**Comment by sergei-lapin** [comment] 2022-09-22 15:06
Hi! Are there any plans for new release with this fix included?
