### ISSUE TITLE
Consider formatting partial files

### ISSUE THREAD

**Issue by ZacSweers** [facebookincubator/ktfmt#322] opened 2022-05-30 01:27 UTC
GJF supports specifying specific lines (`--lines`) or offests (`--offset`) on a best-effort basis, which is helpful for partial commits in VCS. They even have a helpful python snippet to apply formats to changed lints from a diff ([link](https://github.com/google/google-java-format/blob/master/scripts/google-java-format-diff.py)). Would you consider supporting the same?

Their docs: https://github.com/google/google-java-format#from-the-command-line

**Comment by cgrushko** [comment] 2022-05-30 07:12
Thanks for the suggestion! this looks like a duplicate of #218.

**Closed** 2022-05-30 07:13 UTC
