### ISSUE TITLE
v0.40 with spotless wrong format style, detekt issue Unexpected spacing after "(" [SpacingAroundParens]

### ISSUE THREAD

**Issue by Leon406** [facebookincubator/ktfmt#350] opened 2022-09-13 01:50 UTC
spotless config

```
spotless {
    java {
        target "src/**/*.java"
        // https://github.com/google/google-java-format/releases
        googleJavaFormat('1.15.0').aosp()
    }
    kotlin {
        target "src/**/*.kt"
        // https://github.com/facebookincubator/ktfmt/releases
        ktfmt('0.40').kotlinlangStyle()
    }
}

```

before:

    private val ENCODING_TABLE =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#$%&()*+,./:;<=>?@[]^_`{|}~\"".toByteArray()
    

after：

    private val ENCODING_TABLE =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#$%&()*+,./:;<=>?@[]^_`{|}~\"".toByteArray(
        )
    

before:

        val rsp =
            """
            HTTP/1.1 200 OK
            Access-Control-Allow-Credentials: true
            Access-Control-Allow-Methods: GET, POST, OPTIONS
            Access-Control-Allow-Origin: *
            Connection: close
        """.trimIndent()

after:

        val rsp =
            """
            HTTP/1.1 200 OK
            Access-Control-Allow-Credentials: true
            Access-Control-Allow-Methods: GET, POST, OPTIONS
            Access-Control-Allow-Origin: *
            Connection: close
        """.trimIndent(
            )

**Comment by davidtorosyan** [comment] 2022-09-13 16:50
Thanks for reporting! Closing as duplicate of #348, which has been fixed.

**Closed by davidtorosyan** 2022-09-13 16:50 UTC
