### ISSUE TITLE
Crash when formatting JetpackCompose code

### ISSUE THREAD

**Issue by bethcutler** [facebookincubator/ktfmt#196] opened 2021-03-22 22:00 UTC
For this sample code:

```kotlin
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

object FooBar {
  fun doFoo(): @Composable (Modifier) -> Unit {
    return { modifier -> println(modifier) }
  }
}
```

we get an error when formatting:
```
com.google.googlejavaformat.FormattingError: 6:28: error: expected token: 'Modifier'; generated ( instead

        at com.google.googlejavaformat.OpsBuilder.token(OpsBuilder.java:318)
        at com.facebook.ktfmt.KotlinInputAstVisitorBase.token(KotlinInputAstVisitorBase.kt:2218)
        at com.facebook.ktfmt.KotlinInputAstVisitorBase.token$default(KotlinInputAstVisitorBase.kt:2217)
        at com.facebook.ktfmt.KotlinInputAstVisitorBase.visitFunctionType(KotlinInputAstVisitorBase.kt:2007)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitFunctionType(KtVisitorVoid.java:941)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitFunctionType(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtFunctionType.accept(KtFunctionType.java:64)
        at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:60)
        at com.facebook.ktfmt.KotlinInputAstVisitorBase.visitTypeReference(KotlinInputAstVisitorBase.kt:181)
    ...
```

I have not found a workaround for this issue, and this pattern occurs in a handful of files... so it's a high priority for us.

**Comment by JavierSegoviaCordoba** [comment] 2021-03-22 22:13
I haven't played a lot with Compose, but that is not the same that this?

```
object FooBar {
    
  @Composable
  fun DoFoo(): (Modifier) -> Unit {
    return { modifier -> println(modifier) }
  }
}
```

**Comment by bethcutler** [comment] 2021-03-23 17:50
I don't know much about Compose either, but I am told that those two locations for the annotation have different meanings.

In any case, this is valid Kotlin code, so the formatter should be able to handle it gracefully.

**Comment by cgrushko** [comment] 2021-03-23 20:42
@bethcutler I believe this is a duplicate of https://github.com/facebookincubator/ktfmt/issues/186, fixed in https://github.com/facebookincubator/ktfmt/commit/f6c762acef72cd6e291926474925560d95c1038a and released in https://github.com/facebookincubator/ktfmt/releases/tag/v0.22.

The provided example seems to be working for me, can you give 0.22 a try?

**Closed by cgrushko** 2021-03-23 20:42 UTC
