### ISSUE TITLE
Support formatting .kts files

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#163] opened 2021-01-04 22:27 UTC
If I try to run ktfmt on a `.kts` file, it doesn't like the fact that the script contains top-level statements. For example:

```
$ echo 'println("Hello world")' > demo.kts
$ java -jar ktfmt-0.19-jar-with-dependencies.jar demo.kts
demo.kts:1:1: error: Expecting a top level declaration
```

It'd be nice to be able to auto-format Kotlin scripts, particularly `build.gradle.kts`.

**Comment by cgrushko** [comment] 2021-01-04 22:31
Duplicate of #35

**Comment by cgrushko** [comment] 2021-01-04 22:31
I updated the title of #35 so it's easier to find in the future. Thanks for the report!

**Closed by cgrushko** 2021-01-04 22:31 UTC
